apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}starwars-ui
  labels:
    app: starwars-ui
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: starwars-ui
  template:
    metadata:
      labels:
        app: starwars-ui
    spec:
      containers:
      - name: starwars-ui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
